### ISSUE TITLE
Show error if an app is no longer secure

### ISSUE THREAD

**Issue by mattstauffer** [tightenco/checkmate#23]
E.g. if an app is on Laravel 5.4 and that's not maintained anymore.

This may require us to occasionally update a stored-in-code table matching each version with its security expiration date.

**Comment by heggern** [comment]
Hi. Made a solution for this, and some adjustments for the readme, but I'm not able to create a Pull Request. Is this repo closed for contribution?

**Comment by mattstauffer** [comment]
@heggern It shouldn't be; what's happening when you try?

**Comment by heggern** [comment]
Tried to push my branch `fix/insecure`, to create a PR based on that

The response:
```
ERROR: Permission to tighten/checkmate.git denied to heggern.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by mattstauffer** [comment]
@heggern Ah! Check these instructions out: https://mattstauffer.com/blog/how-to-contribute-to-an-open-source-github-project-using-your-own-fork/

**Comment by heggern** [comment]
@mattstauffer Aha! Sorry about that. Must have missed that one. Nothing in CONTRIBUTING.md :) I'll fork away!
